backend:
  name: test-repo
  branch: master # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: pages
    label: Pages
    folder: src/pages
    slug: '{{slug}}'
    extension: 'mdx'
    format: 'frontmatter'
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: body
        label: Body
        widget: mdx
