name: Test Example
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Create build directory
        run: npm run build --if-present
      - name: Move to build directory
        run: echo `cd .next`
      - name: Stage file
        run: echo `git add build-manifest.json -f`
      - name: Move file to root
          env:
            ROOT_DIR: __dirname
        run: echo `git mv build-manifest.json ${ROOT_DIR}`
