name: Test Example
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Create build directory
        run: npm run build --if-present
      - name: Move to build directory
        run: echo `cd .next`
      - name: Stage file
        run: echo `git add build-manifest.json -f`
      - name: Move file to root
        env:
          ROOT_DIR: __dirname
        run: echo `git mv build-manifest.json ${ROOT_DIR}`
      - uses: actions/checkout@v2
        name: Move to desired branch
        ref: 'test3'
      - uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          # add: 'src'

          # The name of the user that will be displayed as the author of the commit
          # Default: author of the commit that triggered the run
          # author_name: Your Name

          # The email of the user that will be displayed as the author of the commit
          # Default: author of the commit that triggered the run
          # author_email: mail@example.com

          # The local path to the directory where your repository is located. You should use actions/checkout first to set it up
          # Default: '.'
          # cwd: './path/to/the/repo'

          # Whether to use the --force option on `git add`, in order to bypass eventual gitignores
          # Default: false
          force: true

          # The message for the commit
          # Default: 'Commit from GitHub Actions'
          message: 'Update manifest file'

          # Name of the branch to use, if different from the one that triggered the workflow
          # Default: the branch that triggered the workflow (from GITHUB_REF)
          ref: 'test3'

          # The arguments for the `git rm` command (see the paragraph below for more info)
          # Default: ''
          # remove: "./dir/old_file.js"
          # Name of the tag to add to the new commit (see the paragraph below for more info)
          # Default: ''
          # tag: "v1.0.0"

        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
