name: Test Example
on: pull_request

jobs:
  first_job:
    name: My first job
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Print a greeting
      - run: yarn build
