name: Test Example
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Create build directory
        run: npm run build --if-present
      # - name: Make a file
      #   run: echo "123" > ./file.txt
      - name: Move to build directory
        run: echo `cd .next`
      - name: Stage file
        run: echo `git add build-manifest.json -f`
      - name: Move file to root
        env:
          ROOT_DIR: __dirname
        run: echo `the root dir is ${ROOT_DIR} && git mv build-manifest.json ${ROOT_DIR}`
      - name: Move to desired branch
        uses: actions/checkout@v2
        ref: 'test3'
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          force: true
          message: 'Your commit message'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
